enable-module-update = true # set this to false if you do not want to receive updates for the module
parallel-jobs = 1

patches-source = "crimera/piko"
cli-source = "MorpheApp/morphe-desktop"
rv-brand = "Piko"

# patches-version = "dev"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Instagram]
#uptodown-dlurl = "https://instagram.en.uptodown.com/android"
direct-dlurl = "https://cloud.doley.qzz.io/f/qlFr/com.instagram.android-439.0.0.37.89-arm64-v8a.apkm"
#dpi = "480-640dpi"
arch = "arm64-v8a"
version = "439.0.0.37.89"

[Twitter]
# uptodown-dlurl = "https://twitter.en.uptodown.com/android"
direct-dlurl = "https://cloud.doley.qzz.io/f/k5H9/com.twitter.android-12.19.1-release.0-arm64-v8a.apkm"
arch = "arm64-v8a"
